name: gscreen
channels:
  - conda-forge
dependencies:
  - python=3.9
  - openbabel=3
  - numpy>=1.20
  - scipy
  - networkx
  - pandas
  - matplotlib
  - seaborn
  - joblib
  - tqdm
  - typer
  - jupyter
  - mypy
  - pip
  - pip:
      - file-read-backwards
